spring:
  profiles:
    include: ad-reach-redis-client-local, launch-darkly-dev
feign:
  client:
    config:
      default:
        loggerLevel: full
server:
  port: 9094
management:
  server:
    port: 9095
blaze:
  ad-reach-synchronizer:
    reach-sync-lag: 0
  data-exchanger:
    endpoint: localhost:8097
  redis:
    decision-cluster:
      nodes:
        - localhost:6379
      maxRedirects: 10
      default-timeout-mills: 2000
