spring:
  application:
    name: blaze-reach-synchronizer
  profiles:
    active: local
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration
  data:
    redis:
      repositories:
        enabled: false
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    enable:
      all: false
      system: true
      http: true
      jvm:
        memory: true
        gc: true
      tomcat: true
      blaze: true
      lettuce: true
    distribution:
      percentiles-histogram:
        lettuce: true
        blaze: true
  endpoint:
    health:
      show-details: always
blaze:
  redis:
    reach-cluster:
      timeout-mills: 10000
    decision-cluster:
      maxRedirects: 10
      timeout-mills: 500
      default-timeout-mills: 2000
  data-exchanger:
    endpoint: adtech-blaze-data-exchanger-service.internal.hotstar.com
    retryer:
      period: 100
      maxPeriod: 1000
      maxAttempts: 3
  ad-reach-synchronizer:
    metrics-prefix: blaze
    executor:
      core-pool-size: 4
      max-pool-size: 16
      keep-alive-seconds: 60
      queue-capacity: 20000
    load.ad-model: 10000
    schedule:
      reach-sync-delay: 30000
