spring:
  profiles:
    include: ad-model-client-local, ad-redis-client-local, launch-darkly-dev
feign:
  client:
    config:
      default:
        loggerLevel: full
server:
  port: 9092
management:
  server:
    port: 9093
blaze:
  ad-reach-synchronizer:
    reach-sync-lag: 0
  data-exchanger:
    endpoint: localhost:8097
