spring:
  profiles:
    include: ad-reach-redis-client-prod, launch-darkly-prod
blaze:
  redis:
    decision-cluster:
      nodes:
        - ad-blaze-ds-ad-prod.45zxvp.clustercfg.aps1.cache.amazonaws.com:6379