spring:
  profiles:
    include: ad-reach-redis-client-load, launch-darkly-nonprod
blaze:
  redis:
    decision-cluster:
      nodes:
        - ad-blaze-ds-ad-load.yi9rtn.clustercfg.apse1.cache.amazonaws.com:6379
      maxRedirects: 10
      default-timeout-mills: 2000