 blaze:
  data-exchanger:
    endpoint: adtech-blaze-data-exchanger-service.internal.sgp.hotstar.com
  redis:
    decision-cluster:
      nodes:
        - ad-blaze-ds-ad-prod.45zxvp.clustercfg.aps1.cache.amazonaws.com:6379
