spring:
  application:
    name: blaze-reach-synchronizer
  profiles:
    active: local
    group:
      dev: ad-reach-redis-client-dev, launch-darkly-dev
      local: ad-reach-redis-client-local, launch-darkly-dev
      pp: ad-reach-redis-client-pp, launch-darkly-nonprod
      prod: ad-reach-redis-client-prod, launch-darkly-prod
      prod-eks: ad-reach-redis-client-prod, launch-darkly-prod
      load: ad-reach-redis-client-load, launch-darkly-nonprod
      qa: ad-reach-redis-client-qa, launch-darkly-nonprod
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration
      - org.springframework.boot.autoconfigure.task.TaskSchedulingAutoConfiguration
  data:
    redis:
      repositories:
        enabled: false
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    enable:
      all: false
      system: true
      http: true
      jvm:
        memory: true
        gc: true
      tomcat: true
      blaze: true
      lettuce: true
    distribution:
      percentiles-histogram:
        lettuce: true
        blaze: true
  endpoint:
    health:
      show-details: always
blaze:
  redis:
    reach-cluster:
      timeout-mills: 10000
    decision-cluster:
      maxRedirects: 10
      timeout-mills: 500
      default-timeout-mills: 2000
  data-exchanger:
    endpoint: adtech-blaze-data-exchanger-service.internal.hotstar.com
    retryer:
      period: 100
      maxPeriod: 1000
      maxAttempts: 3
  ad-reach-synchronizer:
    metrics-prefix: blaze
    load:
      ad-model: 10000
    schedule:
      reach-sync-delay: 30000
