spring:
  profiles:
    include: ad-reach-redis-client-pp, launch-darkly-nonprod
blaze:
  redis:
    decision-cluster:
      nodes:
        - ad-blaze-ds-ad-pp.mtjguk.clustercfg.aps1.cache.amazonaws.com:6379