spring:
  profiles:
    include: ad-reach-redis-client-dev, launch-darkly-dev
blaze:
  redis:
    decision-cluster:
      nodes:
        - ad-blaze-ds-ad-dev.mtjguk.clustercfg.aps1.cache.amazonaws.com:6379
      maxRedirects: 10
      default-timeout-mills: 2000