spring:
  profiles:
    include: ad-model-repository-ro-qa, ad-redis-client-qa, allocation-plan-client-qa
blaze:
  match-progress-model:
    s3:
      region: us-east-1
      bucket: adtech-ml-perf-ads-us-east-1-preprod-v1
      path: concurrency_progress/stat_progress.csv
  ad-crash-model:
    s3:
      region: us-east-1
      bucket: adtech-ml-perf-ads-us-east-1-preprod-v1
      path: bingyang/ad_crash/test/part-00000-db2adcaf-df2b-4c2f-9935-f5f4072bd422-c000.csv
