spring:
  profiles:
    active: local
  application:
    name: "blaze-data-exchanger"
logging:
  level:
    org:
      hibernate.SQL: ERROR
      hibernate.type.descriptor.sql.BasicBinder: ERROR
      springframework: WARN
      springframework.boot.autoconfigure: ERROR
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    enable:
      all: false
      system: true
      http: true
      tomcat: true
      blaze: true
      jvm:
        memory: true
        gc: true
      cache: true
    distribution:
      percentiles-histogram:
        http: true
  endpoint:
    health:
      show-details: always
server:
  tomcat:
    mbeanregistry:
      enabled: true
blaze:
  redis:
    master-replica:
      enable: true
    beacon-cluster:
      enable: true
    reach-cluster:
      enable: true
      timeout-mills: 6000
