spring:
  profiles:
    include: ad-model-repository-ro-pp, ad-redis-client-pp, allocation-plan-client-pp
blaze:
  match-progress-loader:
    bucket-name: adtech-ml-perf-ads-us-east-1-preprod-v1
    s3-region: us-east-1
    path: concurrency_progress/stat_progress.csv