spring:
  profiles:
    include: ad-model-repository-ro-prod, ad-redis-client-prod, allocation-plan-client-prod, ad-model-client-prod
blaze:
  match-progress-model:
    s3:
      region: us-east-1
      bucket: adtech-ml-perf-ads-us-east-1-prod-v1
      path: live_ads_progress/avg_progress_70_90_csv_format/{date}.csv
  ad-crash-model:
    s3:
      bucket: adtech-ml-perf-ads-us-east-1-prod-v1
      path: data/ads_crash/distribution/switch_result/{date}.csv
      region: us-east-1
