server:
  port: 8097
management:
  server:
    port: 8197
spring:
  profiles:
    include: ad-model-repository-local, ad-redis-client-local, allocation-plan-client-local
blaze:
  match-progress-loader:
    bucket-name: adtech-blaze-ad-model-pp
    s3-region: ap-southeast-1
    path: break_progress/{date}.csv