blaze:
  ad-ingester-service:
    schedule:
      concurrency-sync-delay: 5000
    concurrency:
      inject:
        enable: true
  redis:
    master-replica:
      master:
        host: adtech-blaze-ad-qa.mtjguk.ng.0001.aps1.cache.amazonaws.com
        port: 6379
      replicas:
        - host: adtech-blaze-ad-qa-ro.mtjguk.ng.0001.aps1.cache.amazonaws.com
          port: 6379
pulse:
  counter-service:
    endpoint: http://pulse-counter.internal.hotstar.com
