blaze:
  ad-ingester-service:
    swagger:
      enable: false
  redis:
    master-replica:
      master:
        host: adtech-blaze-ad-prod.qneeam.ng.0001.apse1.cache.amazonaws.com
        port: 6379
      replicas:
        - host: adtech-blaze-ad-prod-ro.qneeam.ng.0001.apse1.cache.amazonaws.com
          port: 6379
pulse:
  counter-service:
    endpoint: http://pulse-counter.internal.hotstar.com
    readTimeout: 5000
