spring:
  profiles:
    include: ad-redis-client-pp
pulse:
  counter-service:
    endpoint: http://pulse-counter.internal.hotstar.com
blaze:
  redis:
    master-replica:
      master:
        host: adtech-blaze-ad-pp.mtjguk.ng.0001.aps1.cache.amazonaws.com
        port: 6379
      replicas:
        - host: adtech-blaze-ad-pp-ro.mtjguk.ng.0001.aps1.cache.amazonaws.com
          port: 6379
      default-timeout-mills: 2000