spring:
  profiles:
    include: ad-model-client-qa, ad-redis-client-qa
blaze:
  ad-ingester-service:
    schedule:
      concurrency-sync-delay: 5000
      impression-sync-delay: 5000
pulse:
  counter-service:
    endpoint: http://pf-pulse-counter-service-qa.pp.hotstar-labs.com
