export PROFILE="dev"
export JVM_OPTS="-Xms3072m -Xmx3072m -XX:+UseG1GC"
export ADS_ENV_NAMESPACE_NAME="adtech-in-dev-aps1"
export ADS_ENV_SERVICE_HOSTNAME="adtech-blaze-allocation-planner-dev.pp.hotstar-labs.com"
export ADS_ENV_RESOURCES_LIMIT_MEMORY="4096Mi"
export ADS_ENV_RESOURCES_LIMIT_CPU=2
export ADS_ENV_REQUESTS_LIMIT_MEMORY="4096Mi"
export ADS_ENV_REQUESTS_LIMIT_CPU=2
export ADS_ENV_STAGE="DEV"
export ADS_ENV_HPA_MIN_PODS=1
export ADS_ENV_HPA_MAX_PODS=1
export ACCESS_LOGS_BUCKET_NAME="all-elb-logs-aps1"
