spring:
  profiles:
    include: ad-model-repository-local, ad-model-client-local, allocation-plan-client-local
blaze:
  data-exchanger:
    endpoint: localhost:8097
  schedule:
    load.ad-model: 10000
    load.break-progress-model: 5000
    load.break-definition: 5000
feign:
  client:
    config:
      default:
        loggerLevel: full
server:
  port: 9090
management:
  server:
    port: 9091
logging:
  level:
    root: info
