launch:
  darkly:
    vaultConfigPath:
    enabled:
      countries: IN
      platforms:
    user: ads-prod
    countryCode: in
    filters:
      region: ap-southeast-1
    relay:
      host: https://launch-darkly-relay.hotstar-labs.com
      sdkkey: ${LAUNCH_DARKLY_SDK_KEY}
      port: 80
      streamingDelay: 500
      enabled: true
      backoff:
        retry: 3
        interval: 3000
    ddb:
      ttl: 30000
      enabled: false
    scheduler:
      delay: 900000