spring:
  profiles:
    include: ad-model-repository-prod, ad-model-client-prod, allocation-plan-client-prod, launch-darkly-prod, ad-reach-redis-client-prod, allocation-data-client-prod
blaze:
  ad-allocation-planner:
    gap-time: 30

