spring:
  profiles:
    active: local
    group:
     local: ad-model-repository-local, ad-model-client-local, allocation-plan-client-local, launch-darkly-dev, ad-reach-redis-client-local
     dev: ad-model-repository-dev, ad-model-client-dev, allocation-plan-client-dev, launch-darkly-dev, ad-reach-redis-client-dev, allocation-data-client-dev
     qa: ad-model-repository-qa, ad-model-client-qa, allocation-plan-client-qa, launch-darkly-nonprod, ad-reach-redis-client-qa, allocation-data-client-qa
     pp: ad-model-repository-pp, ad-model-client-pp, allocation-plan-client-pp, launch-darkly-nonprod, ad-reach-redis-client-pp, allocation-data-client-pp
     load: ad-model-repository-load, ad-model-client-load, allocation-plan-client-pp, launch-darkly-nonprod, ad-reach-redis-client-load, allocation-data-client-pp
     pp-test: ad-model-repository-pp, ad-model-client-pp, allocation-plan-client-pp, launch-darkly-nonprod, ad-reach-redis-client-pp, allocation-data-client-pp
     prod: ad-model-repository-prod, ad-model-client-prod, allocation-plan-client-prod, launch-darkly-prod, ad-reach-redis-client-prod, allocation-data-client-prod
     prod-eks: ad-model-repository-prod, ad-model-client-prod, allocation-plan-client-prod, launch-darkly-prod, ad-reach-redis-client-prod, allocation-data-client-prod
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration
  data:
    redis:
      repositories:
        enabled: false
  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 1
  application:
    name: blaze-allocation-planner
  task:
    scheduling:
      shutdown:
        await-termination: true
        await-termination-period: 180s
    execution:
      shutdown:
        await-termination: true
        await-termination-period: 90s
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    enable:
      all: false
      system: true
      http: true
      blaze: true
      jvm:
        memory: true
        gc: true
      tomcat: true
  endpoint:
    health:
      show-details: always
blaze:
  ad-allocation-planner:
    gap-time: 300
    metrics-prefix: blaze
    executor:
      core-pool-size: 4
      max-pool-size: 16
      keep-alive-seconds: 60
      queue-capacity: 20000
    schedule:
      load.ad-model: 10000
      load.break-progress-model: 300000
      load.break-definition: 300000
      manager: 3000
      worker: 500
  data-exchanger:
    endpoint: adtech-blaze-data-exchanger-service.internal.hotstar.com
    retryer:
      period: 100
      maxPeriod: 1000
      maxAttempts: 3
  redis:
    reach-cluster:
      enable: true
      timeout-mills: 20000
feign:
  client:
    config:
      ad-data-exchanger:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
logging:
  level:
    com.hotstar.launchdarkly: WARN
