spring:
  profiles:
    include: ad-model-repository-prod, ad-model-client-prod, allocation-plan-client-prod
blaze:
  data-exchanger:
    endpoint: adtech-blaze-data-exchanger-apse1.hotstar-labs.com


